services:
  ai-defra-search-frontend:
    build:
      target: development
      context: ../../ai-defra-search-frontend
    ports:
      - '3000:3000'
    links:
      - 'redis:redis'
    depends_on:
      redis:
        condition: service_started
    env_file:
      - "../.env"
    volumes:
      - ../../ai-defra-search-frontend/src/:/home/node/src
      - ../../ai-defra-search-frontend/package.json:/home/node/package.json
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
    networks:
      - ai-defra-search
