x-common-postgres: &common-postgres
  POSTGRES_HOST: ${AI_DEFRA_SEARCH_POSTGRES_HOST:-postgres}
  POSTGRES_USER: ${AI_DEFRA_SEARCH_POSTGRES_USER:-postgres}
  POSTGRES_PORT: ${AI_DEFRA_SEARCH_POSTGRES_PORT:-5432}
  POSTGRES_PASSWORD: ${AI_DEFRA_SEARCH_POSTGRES_PASSWORD:-ppp}
  POSTGRES_SSL_MODE: ${AI_DEFRA_SEARCH_POSTGRES_SSL_MODE:-disable}
  POSTGRES_DB: ${POSTGRES_DB:-ai_defra_search_data}
services:
  ai-defra-search-data-db-migrator:
    build:
      context: ../services/ai-defra-search-data/migrator
    container_name: ai-defra-search-data-db-migrator
    depends_on:
      postgres:
        condition: service_healthy
    environment: *common-postgres
    volumes:
      - ../services/ai-defra-search-data/changelog:/liquibase/changelog
    networks:
      - ai-defra-search

  ai-defra-search-data:
    build:
      context: ../services/ai-defra-search-data
      target: development
    ports:
      - 8085:8085
    links:
      - "localstack:localstack"
      - "mongodb:mongodb"
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
      postgres:
        condition: service_healthy
      ai-defra-search-data-db-migrator:
        condition: service_completed_successfully
    env_file:
      - "../.env"
    entrypoint: []
    environment:
      <<: *common-postgres
      PORT: ${PORT:-8085}
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/}
      HOST: ${HOST:-0.0.0.0}
      LOCALSTACK_URL: ${LOCALSTACK_URL:-http://localstack:4566}
      POSTGRES_DB: ${POSTGRES_DB:-ai_defra_search_data}
      LOG_CONFIG: logging-dev.json
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "/home/nonroot/.venv/bin/ai-defra-search-data"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 5s
      start_period: 10s
      retries: 3
    volumes:
      - ../services/ai-defra-search-data/app:/home/nonroot/app
    develop:
      watch:
        - action: rebuild
          path: ../services/ai-defra-search-data/pyproject.toml
          target: /home/nonroot/pyproject.toml
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ai-defra-search"
      - "traefik.http.routers.data.rule=Host(`data.localhost`)"
      - "traefik.http.routers.data.entrypoints=web"
      - "traefik.http.services.data.loadbalancer.server.port=8085"
    networks:
      - ai-defra-search
