services:
  ai-defra-search-frontend:
    build:
      target: development
      context: ../services/ai-defra-search-frontend
    ports:
      - '3000:3000'
    links:
      - 'redis:redis'
    depends_on:
      redis:
        condition: service_started
      ai-defra-search-knowledge:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      start_period: 10s
      retries: 3
    env_file:
      - "../.env"
    volumes:
      - ../services/ai-defra-search-frontend/src/:/home/node/src
      - ../services/ai-defra-search-frontend/package.json:/home/node/package.json
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
      DATA_API_URL: ${DATA_API_URL:-http://ai-defra-search-data:8085}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ai-defra-search"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - ai-defra-search
