services:
  cdp-uploader:
    image: defradigital/cdp-uploader:${CDP_UPLOADER_VERSION:-latest}
    ports:
      - '7337:7337'
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      AWS_EMF_AGENT_ENDPOINT: ""  # disable CloudWatch EMF in local (no agent on 25888)
      PORT: 7337
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
      MOCK_VIRUS_SCAN_ENABLED: true
      MOCK_VIRUS_RESULT_DELAY: 3
      SQS_ENDPOINT: http://localstack:4566
      S3_ENDPOINT: http://localstack:4566
      AWS_REGION: eu-west-2
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      APP_BASE_URL: http://cdp-uploader:7337
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ai-defra-search"
      - "traefik.http.routers.cdp-uploader.rule=Host(`cdp-uploader.localhost`)"
      - "traefik.http.routers.cdp-uploader.entrypoints=web"
      - "traefik.http.services.cdp-uploader.loadbalancer.server.port=7337"
    networks:
      - ai-defra-search
