# Override for running frontend tests from devcontainer - avoids host path mount issues.
# Use: docker compose -f compose.yml -f compose.test-frontend.yaml run --build --rm ai-defra-search-frontend
services:
  ai-defra-search-frontend:
    command: npm run test
    volumes: !reset []
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
      DATA_API_URL: ${DATA_API_URL:-http://ai-defra-search-data:8085}
      PROTOTYPE_PASSWORD: correctpassword
      AUTH_ENABLED: false
      MS_ENTRA_TENANT_ID: cb2d380f-8056-494b-bfad-cfcaf767c0b3
      MS_ENTRA_CLIENT_ID: 28434819-c64a-4b95-bb23-0f6202bcfc02
      MS_ENTRA_CLIENT_SECRET: client-secret-value
      MS_ENTRA_REDIRECT_HOST: http://localhost:3000
